Vagrant.configure("2") do |config|

  # MX1
  config.vm.define "mx1" do |mx1|
    mx1.vm.box = "ubuntu/focal64"
    mx1.vm.hostname = "mx1.lvr-corp.com"
    mx1.vm.network "private_network", ip: "192.168.56.20"
    mx1.vm.provider "virtualbox" do |vb|
      vb.memory = "512"
      vb.cpus = "1"
    end
  end

  # MX2
  config.vm.define "mx2" do |mx2|
    mx2.vm.box = "ubuntu/focal64"
    mx2.vm.hostname = "mx2.lvr-corp.com.fr"
    mx2.vm.network "private_network", ip: "192.168.56.30"
    mx2.vm.provider "virtualbox" do |vb|
      vb.memory = "512"
      vb.cpus = "1"
    end
  end

end
