Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.hostname = "srv-dns"

  config.vm.network "public_network", bridge: "wlp0s20f3", ip: "192.168.1.200", netmask: "24"
  config.vm.network "private_network", ip: "192.168.56.10"
  
  config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--cpus", "1"]
    vb.memory = "512"
  end
end
