---
- hosts: dns
  become: true

  tasks:
    - name: Create admin user
      user:
        name: admin
        password: "{{ 'Azerty1' | password_hash('sha512') }}"
        shell: /bin/bash
        groups: sudo
        append: true

    - name: Install DNS server
      apt:
        name: bind9
        state: present

    - name: Configure DNS zone
      template:
        src: templates/named.conf.local.j2
        dest: /etc/bind/named.conf.local
        owner: root
        group: bind
        mode: '0644'

    - name: Configure DNS records
      template:
        src: templates/lvr-corp.com.j2
        dest: /var/lib/bind/lvr-corp.com.zone
        owner: bind
        group: bind
        mode: '0644'

    - name: Restart DNS service
      service:
        name: bind9
        state: restarted
